services:
  - type: web
    name: rokai-dashboard
    env: node
    plan: starter
    branch: nextjs-dashboard
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    rootDir: .
